/**
 * Stalker API
 * API di Stalker di Imola Informatica sviluppato da qbteam
 *
 * The version of the OpenAPI document: 1.0.0
 * Contact: qbteamswe@gmail.com
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */


/**
 * Generic access to an organization or a place of it.
 */
export interface Access {
    id: number;
    accessDiscriminator: string;
    /**
     * Date and time of the moment in which the user entered the place.
     */
    entranceTimestamp: Date;
    /**
     * Date and time of the moment in which the user left the place.
     */
    exitTimestamp: Date;
}

