/**
 * Stalker API
 * API di Stalker di Imola Informatica sviluppato da qbteam
 *
 * The version of the OpenAPI document: 1.0.0
 * Contact: qbteamswe@gmail.com
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */


/**
 * Link between the user and the organization: only the organization which users sets to be their favorite can track their movements.
 */
export interface Favorite {
    /**
     * Authentication service\'s user unique identifier.
     */
    userId: string;
    /**
     * Unique identifier of the organization the user sets as favorite.
     */
    organizationId: number;
    /**
     * When the favorite was added by the user.
     */
    creationDate: Date;
}

