/**
 * Stalker API
 * API di Stalker di Imola Informatica sviluppato da qbteam
 *
 * The version of the OpenAPI document: 1.0.0
 * Contact: qbteamswe@gmail.com
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */


/**
 * Request object for creating a new deletion request for the organization. The request will be analyzed by a Stalker administrator.
 */
export interface OrganizationDeletionRequest {
  /**
   * Unique identifier of the organization.
   */
  organizationId: number;
  /**
   * Request reason for the deletion request.
   */
  requestReason: string;
  /**
   * Authentication service\'s administrator unique identifier.
   */
  administratorId?: string;
}
