/**
 * Stalker API
 * API di Stalker di Imola Informatica sviluppato da qbteam
 *
 * The version of the OpenAPI document: 1.0.0
 * Contact: qbteamswe@gmail.com
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */


/**
 * Movement in an organization.
 */
export interface OrganizationMovement { 
    /**
     * Token generated by the server when the user entered in the organization. It is required only to track an exit movement. If this property is not empty in an entrance movement it will not be considered.
     */
    exitToken?: string;
    /**
     * Date and time of the moment in which the user entered the place.
     */
    timestamp: Date;
    /**
     * Type of movement. It can be: - Entrance: 1 - Exit: -1
     */
    movementType: number;
    /**
     * Unique identifier of the organization in which the user had access.
     */
    organizationId: number;
    /**
     * User unique identifier from the authentication server of the organization.
     */
    orgAuthServerId?: string;
}

