/**
 * Stalker API
 * API di Stalker di Imola Informatica sviluppato da qbteam
 *
 * The version of the OpenAPI document: 1.0.0
 * Contact: qbteamswe@gmail.com
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */


/**
 * Credentials for authenticating to the organizations\'s authentication server.
 */
export interface OrganizationAuthenticationServerCredentials { 
    /**
     * Username of the administrator account in the organizations\'s authentication server.
     */
    username: string;
    /**
     * Password of the administrator account in the organizations\'s authentication server.
     */
    password: string;
}

