/**
 * Stalker API
 * API di Stalker di Imola Informatica sviluppato da qbteam
 *
 * The version of the OpenAPI document: 1.0.0
 * Contact: qbteamswe@gmail.com
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */
import { OrganizationAuthenticationServerCredentials } from './organizationAuthenticationServerCredentials';


/**
 * Data for requesting information about users of an organization.
 */
export interface OrganizationAuthenticationServerRequest { 
    organizationCredentials: OrganizationAuthenticationServerCredentials;
    /**
     * Unique identifier of an organization.
     */
    organizationId: number;
    /**
     * List of ids of users to get their information.
     */
    orgAuthServerIds: Array<string>;
}

