/**
 * Stalker API
 * API di Stalker di Imola Informatica sviluppato da qbteam
 *
 * The version of the OpenAPI document: 1.0.0
 * Contact: qbteamswe@gmail.com
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */


/**
 * Number of people currently inside the organization\'s trackingArea.
 */
export interface OrganizationPresenceCounter { 
    /**
     * Unique identifier of the organization.
     */
    organizationId: number;
    /**
     * Number of people currently inside the organization\'s trackingArea.
     */
    counter: number;
}

