/**
 * Stalker API
 * API di Stalker di Imola Informatica sviluppato da qbteam
 *
 * The version of the OpenAPI document: 1.0.0
 * Contact: qbteamswe@gmail.com
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */


/**
 * What can or cannot do an organization\'s administrator.
 */
export interface Permission {
    /**
     * Authentication service\'s administrator unique identifier.
     */
    administratorId?: string;
    /**
     * Unique identifier of the organization the administrator is part of.
     */
    organizationId: number;
    /**
     * What can or cannot do an organization\'s administrator. Owner is the highest level of permissions while viewer is the lowest.
     */
    permission: Permission.PermissionEnum;
}
export namespace Permission {
    export type PermissionEnum = 'owner' | 'manager' | 'viewer';
    export const PermissionEnum = {
        Owner: 'owner' as PermissionEnum,
        Manager: 'manager' as PermissionEnum,
        Viewer: 'viewer' as PermissionEnum
    };
}


