/**
 * Stalker API
 * API di Stalker di Imola Informatica sviluppato da qbteam
 *
 * The version of the OpenAPI document: 1.0.0
 * Contact: qbteamswe@gmail.com
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */


/**
 * Area of an organization subjected to tracking.
 */
export interface Place { 
    /**
     * Unique identifier for a place of an organization.
     */
    id: number;
    /**
     * Name describing the place. If not set by user it gets automatically filled.
     */
    name?: string;
    /**
     * Unique identifier of the organization the place is part of.
     */
    organizationId: number;
    /**
     * Area subjected to movement tracking of people. It is a collection of (longitude, latitude) pairs consisting in a polygon. The string is expressed in JSON format.
     */
    trackingArea: string;
}

