/**
 * Stalker API
 * API di Stalker di Imola Informatica sviluppato da qbteam
 *
 * The version of the OpenAPI document: 1.0.0
 * Contact: qbteamswe@gmail.com
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */


/**
 * Represents a row in the report generated for an user by the viewer administrator.
 */
export interface TimePerUserReport {
  /**
   * Unique identifier of the place in which the user had access.
   */
  placeId: number;
  /**
   * User unique identifier from the authentication server of the organization.
   */
  orgAuthServerId: string;
  /**
   * Total amount of time (in seconds) spent inside the organization by the user.
   */
  totalTime: number;
}

