/**
 * Stalker API
 * API di Stalker di Imola Informatica sviluppato da qbteam
 *
 * The version of the OpenAPI document: 1.0.0
 * Contact: qbteamswe@gmail.com
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */


export interface User {
    /**
     * Authentication service\'s user unique identifier.
     */
    userId: string;
    /**
     * Organization LDAP server\'s user unique identifier.
     */
    ldapId?: number;
}

