export * from './access.service';
import { AccessService } from './access.service';
export * from './administrator.service';
import { AdministratorService } from './administrator.service';
export * from './favorite.service';
import { FavoriteService } from './favorite.service';
export * from './movement.service';
import { MovementService } from './movement.service';
export * from './organization.service';
import { OrganizationService } from './organization.service';
export * from './place.service';
import { PlaceService } from './place.service';
export * from './presence.service';
import { PresenceService } from './presence.service';
export * from './report.service';
import { ReportService } from './report.service';
export const APIS = [AccessService, AdministratorService, FavoriteService, MovementService, OrganizationService, PlaceService, PresenceService, ReportService];
